/**
 * Copyright (c) 2020, Oracle Corporation and/or its affiliates.
 * Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
 */

/* Jenkinsfile to apply WLS opacthes  */

properties([
    parameters([
        choice(choices: ['Object Storage', 'Shared File System'], description: 'WebLogic patches can be provided via either the pre-authenticated URL for the file in Object Storage (https://<pre-authenticated URL>/opatch.zip) or at a path on the shared file system (under /u01/shared location).', name: 'WLS_Opatches'),
        text(defaultValue: '', description: '''Object Storage: Pre-authenticated URL to download WebLogic Patches. Multiple patches can be provided in separate line.\nShared File System Location: Full path to the location of WebLogic Patches (/u01/shared/path/to/patch.zip). Multiple patches can be provided in separate line.''', name: 'Opatches_Location'),
        booleanParam(defaultValue: true, description: 'Rollback to previous state if Apply Domain fails.', name: 'Rollback_On_Failure'),
//         booleanParam(defaultValue: false, description: 'Scan domain image for security vulnerabilities.', name: 'Scan_Image_Enabled')
    ])
])

def ARGS = ""
pipeline {
    agent {
        node {
            label 'agent-label-slave'
        }
    }
    options {
        skipStagesAfterUnstable()
        disableConcurrentBuilds()
        timestamps()
        warnError('Pipeline error caught')
    }
    environment {
        BUILD_TS = get_build_timestamp()
    }
    stages {
        stage("PRE-CHECK") {
            steps {
                echo "Validating Domain is running... "
                echo "WLS_Opatches: ${params.WLS_Opatches}"
                echo "Opatches_Location: ${params.Opatches_Location}"
                echo "Rollback_On_Failure: ${params.Rollback_On_Failure}"
//                 echo "Scan_Image: ${params.Scan_Image_Enabled}"

                script {
                    if (params.Rollback_On_Failure) {
                        ARGS += "-r "
                    }
//                     if (params.Scan_Image_Enabled) {
//                         ARGS += "-s "
//                     }
                    switch (params.WLS_Opatches) {
                        case 'Shared File System Location':
                                def counter=0;
                                def patch_str="";
                                for ( opatch in params.Opatches_Location.tokenize() )
                                {
                                   if (checkFileExists(opatch)) {
                                      sh "cp $opatch $WORKSPACE"
                                      def base = sh(script: "basename $opatch" , returnStdout: true)
                                      patch_str += env.WORKSPACE+"/"+base+" "
                                   } else {
                                          println "File does not exist: [" + opatch + "]"
                                          error("Build failed")
                                   }
                                }
                                def patch_str_new = '"'+patch_str+'"'
                                ARGS += "-w " + patch_str_new + " "
                                break
                        case 'Object Storage':
                                def counter=0;
                                def patch_str="";
                                for ( opatch in params.Opatches_Location.tokenize() )
                                {
                                    if (isURLValid(opatch)) {
                                      sh "wget $opatch -P $WORKSPACE"
                                      def base = sh(script: "basename $opatch" , returnStdout: true)
                                      patch_str += env.WORKSPACE+"/"+base+" "
                                   } else {
                                      println "URL is invalid: [" + opatch + "]"
                                      error("Build failed")
                                   }
                                }
                                def patch_str_new = '"'+patch_str+'"'
                                ARGS += "-w " + patch_str_new + " "
                                break
                    }
                     println "ARGS: " + ARGS
                    sh "/u01/shared/scripts/pipeline/common/precheck_common.sh ${ARGS}"
                }

            }
            post {
                failure {
                    echo "Failed in pre-check"
                }
                unstable {
                    echo "Unstable in pre-check"
                }
            }
        }
        stage('APPLY_WLS_OPATCHES') {
            steps {
                echo "Install WLS patches... "
                sh "/u01/shared/scripts/pipeline/opatch-update/apply_opatch.sh ${ARGS}"
            }
            post {
                failure {
                    echo "Failed in apply opatch"
                }
                unstable {
                    echo "Unstable in apply opatch"
                }
            }
        }
        /* Scan Image stage:
            Scan the new image for vulnerabilities.
         */
//         stage("SCAN_IMAGE") {
//             steps {
//                 echo "Scanning image for vulnerabilities..."
//                 sh "/u01/shared/scripts/pipeline/common/scan_domain_img_common.sh ${ARGS}"
//             }
//             post {
//                 failure {
//                     echo "Failed in scanning image"
//                 }
//                 unstable {
//                     echo "Unstable in scanning image"
//                 }
//             }
//         }
        stage("OCIR_UPLOAD") {
            steps {
                echo "Pushing Domain image to OCIR... "
                sh "/u01/shared/scripts/pipeline/common/ocir_push_domain_img_common.sh ${ARGS}"
            }
            post {
                failure {
                    echo "Failed in pushing domain to OCIR"
                }
                unstable {
                    echo "Unstable in pushing domain to OCIR"
                }
            }
        }
        stage("TEST_AND_DEPLOY_DOMAIN") {
            steps {
                build job: 'test-and-deploy-domain-job',
                        parameters: [
                                string(name: 'ARGS', value: "${ARGS}"),
                                string(name:'BUILD_TS', value:"${BUILD_TS}"),
                        ]
            }
        }
    }
}
/**
 * Generating build timestamp.
 * This will be used to tag the updated domain docker image.
 */
def get_build_timestamp() {
    Date date = new Date()
    buildTimestamp = date.format('yy-MM-dd_HH-mm-ss')
    println("Generated Build Timestamp: " + buildTimestamp)
    return buildTimestamp
}
/**
 * Check if valid URL.
 * @param str   URL string
 * @return  true if valid, false otherwise.
 */
def Boolean isURLValid(String str)
{
    try {
        new URL(str)
        return true
    } catch (MalformedURLException e) {
        return false
    }
}
/**
 * Check if file exists.
 *
 * @param fileName  Absolute path of file.
 * @return  true if file exists, false otherwise.
 */
def Boolean checkFileExists(String fileName) {
    try {
        File file = new File(fileName)
        return file.exists()
    } catch (Exception e) {
        return false
    }
}
